name: Test and Release

on:
  push:
    paths-ignore:
      - Dockerfile
      - .github/workflows/test-docker.yaml
      - .github/workflows/publish-docker.yaml
      - .github/workflows/cd.yaml

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  APP_NAME: bifravst
  B2C_TENANT: bifravstciusers
  RESOURCE_GROUP_NAME: bifravst
  LOCATION: northeurope
  APP_REG_CLIENT_ID: ${{ secrets.E2E_APP_REG_CLIENT_ID }}
  B2C_CLIENT_SECRET: ${{ secrets.E2E_B2C_CLIENT_SECRET }}
  B2C_TENANT_ID: ${{ secrets.E2E_B2C_TENANT_ID }}
  AZURE_CREDENTIALS: ${{ secrets.E2E_AZURE_CREDENTIALS }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Azure CLI
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.E2E_AZURE_CREDENTIALS }}
      - run: az account list --output table
      - name: Install Azures Functions CLI
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list'
          sudo apt-get update
          sudo apt-get install azure-functions-core-tools-3
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci --no-audit
      - run: npx tsc
      - name: Run Unit Tests
        run: npm test
      - name: Deploy solution
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 18000
          max_attempts: 3
          command: |
            az deployment group create \
              --resource-group ${RESOURCE_GROUP_NAME} \
              --mode Complete \
              --name test-${{ github.sha }} \
              --template-file azuredeploy.json \
              --parameters \
                appName=${APP_NAME} \
                location=${LOCATION} \
                appRegistrationClientId=${APP_REG_CLIENT_ID} \
                b2cTenant=${B2C_TENANT} \
                b2cFlowName=B2C_1_developer
      - name: Deploy Function App
        run: func azure functionapp publish ${APP_NAME}api --typescript
      - name: Determine API endpoint
        run: |
          API_ENDPOINT=https://`az functionapp show -g ${RESOURCE_GROUP_NAME} -n ${APP_NAME}api --query 'defaultHostName' --output tsv | tr -d '\n'`/
          echo "API_ENDPOINT=${API_ENDPOINT}" >> $GITHUB_ENV
      - name: Cache certificates
        uses: actions/cache@v2
        with:
          path: ./certificates
          key: certificates-${{ env.TENANT_ID }}
      - run: |
          ls ./certificates/CA.intermediate.* 1> /dev/null 2>&1
          echo "SKIP_CERT_GENERATION=1" >> $GITHUB_ENV
        continue-on-error: true
      - name: Create Intermediate CA certificate
        if: env.SKIP_CERT_GENERATION != '1'
        run: |
          node cli create-ca-root
          node cli proof-ca-root-possession
          node cli create-ca-intermediate
      - run: |
          TENANT_ID=`echo ${AZURE_CREDENTIALS} | jq -r '.tenantId' | tr -d '\n'`
          echo "TENANT_ID=${TENANT_ID}" >> $GITHUB_ENV
      - name: Run End-to-End Tests
        uses: nick-invision/retry@v2
        env:
          FORCE_COLOR: 3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npm run test:e2e
      - name: Delete device certificates
        run: rm ./certificates/device-*
      - name: Semantic release
        if: success()
        continue-on-error: true
        run: |
          npm i --no-save semantic-release
          npx semantic-release
