name: Publish Docker Image

on:
  push:
    branches:
      - "!saga"
    paths:
      - Dockerfile
      - .github/workflows/test-docker.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build image
        run: |
          docker build -t bifravst/azure-dev .
