name: Test and Release

on:
  push:
    paths-ignore:
      - Dockerfile
      - .github/workflows/test-docker.yaml
      - .github/workflows/publish-docker.yaml
      - .github/workflows/cd.yaml

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  APP_NAME: bifravst
  B2C_TENANT: bifravstciusers
  RESOURCE_GROUP_NAME: bifravst
  APP_REG_CLIENT_ID: ${{ secrets.APP_REG_CLIENT_ID }}
  B2C_CLIENT_SECRET: ${{ secrets.B2C_CLIENT_SECRET }}
  B2C_TENANT_ID: ${{ secrets.B2C_TENANT_ID }}
  AZURE_CREDENTIALS: ${{ secrets.E2E_AZURE_CREDENTIALS }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: az account list --output table
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci --no-audit
      - run: npx tsc
      - run: npm test
      - name: Determine API endpoint
        run: |
          API_ENDPOINT=https://`az functionapp show -g ${RESOURCE_GROUP_NAME} -n ${APP_NAME}api --query 'defaultHostName' --output tsv | tr -d '\n'`/
          echo "::set-env name=API_ENDPOINT::${API_ENDPOINT}"
      - run: npm run test:e2e
      - name: Semantic release
        if: success()
        continue-on-error: true
        run: |
          npm i --no-save semantic-release
          npx semantic-release
